In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [39]:
arr = np.zeros((9, 9))
arr[8,:] = 1 #sets entries in last row to 1
arr[:,0] = np.ones(9)
arr[:,1] = np.ones(9)
arr[:,2] = np.ones(9)
arr[4][5], arr[7][7], arr[1,8] = 1, 1, 1 #sets particular values in the array to 1
print(arr)
plt.spy(arr)
plt.show()

[[ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  1.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]]
